<?php
/**
 * @copyright 2019 Wayfair LLC - All rights reserved
 */

namespace Wayfair\Core\Dto;

class Constants
{
  const UNIT_TYPE_CARTON = 'CARTON';
  const UNIT_TYPE_BAG = 'BAG';
  const UNIT_TYPE_ROLL = 'ROLL';
  const UNIT_TYPE_OTHER = 'OTHER';

  const WEIGHT_UNIT_POUNDS = 'POUNDS';
  const WEIGHT_UNIT_KILOGRAMS = 'KILOGRAMS';

  const LENGTH_UNIT_INCHES = 'INCHES';
  const LENGTH_UNIT_CENTIMETERS = 'CENTIMETERS';

  const FREIGHT_CLASS_CODE_500 = 'CODE_500';
  const FREIGHT_CLASS_CODE_400 = 'CODE_400';
  const FREIGHT_CLASS_CODE_300 = 'CODE_300';
  const FREIGHT_CLASS_CODE_250 = 'CODE_250';
  const FREIGHT_CLASS_CODE_200 = 'CODE_200';
  const FREIGHT_CLASS_CODE_175 = 'CODE_175';
  const FREIGHT_CLASS_CODE_150 = 'CODE_150';
  const FREIGHT_CLASS_CODE_125 = 'CODE_125';
  const FREIGHT_CLASS_CODE_110 = 'CODE_110';
  const FREIGHT_CLASS_CODE_100 = 'CODE_100';
  const FREIGHT_CLASS_CODE_92_5 = 'CODE_92_5';
  const FREIGHT_CLASS_CODE_85 = 'CODE_85';
  const FREIGHT_CLASS_CODE_77_5 = 'CODE_77_5';
  const FREIGHT_CLASS_CODE_70 = 'CODE_70';
  const FREIGHT_CLASS_CODE_65 = 'CODE_65';
  const FREIGHT_CLASS_CODE_60 = 'CODE_60';
  const FREIGHT_CLASS_CODE_55 = 'CODE_55';
  const FREIGHT_CLASS_CODE_50 = 'CODE_50';

  const AVAILABLE_UNIT_TYPES = [
    self::UNIT_TYPE_CARTON,
    self::UNIT_TYPE_BAG,
    self::UNIT_TYPE_ROLL,
    self::UNIT_TYPE_OTHER,
  ];

  const AVAILABLE_WEIGHT_UNITS = [
    self::WEIGHT_UNIT_POUNDS,
    self::WEIGHT_UNIT_KILOGRAMS,
  ];

  const AVAILABLE_LENGTH_UNITS = [
    self::LENGTH_UNIT_INCHES,
    self::LENGTH_UNIT_CENTIMETERS,
  ];

  const AVAILABLE_FREIGHT_CLASSES = [
    self::FREIGHT_CLASS_CODE_500,
    self::FREIGHT_CLASS_CODE_400,
    self::FREIGHT_CLASS_CODE_300,
    self::FREIGHT_CLASS_CODE_250,
    self::FREIGHT_CLASS_CODE_200,
    self::FREIGHT_CLASS_CODE_175,
    self::FREIGHT_CLASS_CODE_150,
    self::FREIGHT_CLASS_CODE_125,
    self::FREIGHT_CLASS_CODE_110,
    self::FREIGHT_CLASS_CODE_100,
    self::FREIGHT_CLASS_CODE_92_5,
    self::FREIGHT_CLASS_CODE_85,
    self::FREIGHT_CLASS_CODE_77_5,
    self::FREIGHT_CLASS_CODE_70,
    self::FREIGHT_CLASS_CODE_65,
    self::FREIGHT_CLASS_CODE_60,
    self::FREIGHT_CLASS_CODE_55,
    self::FREIGHT_CLASS_CODE_50,
  ];

  const SUPPLIER_SHIPPED_ASN = 'SHIPPED_ASN';
  const SHIPPING_WITH_WF = 'wayfair_shipping';
}
