name: Generate PHP Test Artifacts

on:
  workflow_dispatch:

jobs:
  php-test-artifacts:
    # ubuntu 16.04 has PHP 7.0 installed, but it is NOT selected anymore (December 2020).
    # Plenty plugin code must be PHP 7.0 only.
    # other OSes / ubuntu versions will not be compatible.
    runs-on: ubuntu-16.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: switch to php 7.0
        run: sudo update-alternatives --set php /usr/bin/php7.0

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite to generate artifacts
        run: |
          sudo chmod -R 755 .
          ./run_tests testCoverage

      - name: upload the test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test_results
          path: test_results
